### ISSUE TITLE
version problem

### ISSUE THREAD

**Issue by YukiOnGithub** [zardam/numworks-nofrendo#14]
so my numworks is version 16.3.0 and apparently this doesn't work in this version so i just wanted to know if you could make a fix or maybe have a way to downgrade the calculator. Thanks in advance for the help.

**Comment by maelhos** [comment]
oohh dear... poor boy... so since 16.3 Numworks implanted an imovable kernel that is write protected and block third party stuff... u can flash some apps using dfu-utils the way it is specified here https://github.com/numworks/epsilon/blob/master/ion/src/device/README.md (with annoying messages when u turn on and delete app when reseting the calc)
but to go back to older ones u need to use an external chip to write to the flash or find somekind of exploit that i am searching too

**Comment by maelhos** [comment]
@zardam just close, there is nothing to be done exept if u have somekinda pwn

**Comment by YukiOnGithub** [comment]
Oh welp i'll see what i can do thanks again 👍
