### ISSUE TITLE
Adding Save State

### ISSUE THREAD

**Issue by maelhos** [zardam/numworks-nofrendo#8]
Well ... I know, i'm sorry, a lot of people has already asked the dev to add some features and I understand why ... What you've done is awesome !! I'm a junior dev and I just read the code a bit and it seems like nofrendo emulator already feature a savestate implementation, I know you probably don't have the time to implement this but can you give some tips were the calc press is interpreted and sended to the emulator and i will try to do a nice fork featuring this ... i think that nofrendo/event.c is a bit responsible ... but i don't really know ...

Anyway Thanks for this awsome repo
You changed my college classes ;o

**Comment by zardam** [comment]
Keyboard input is converted in emulator events here https://github.com/zardam/numworks-nofrendo/blob/master/nofrendo/epsilon/osd_epsilon.c#L91 you will need to add save state events here.

Then, saving state will be calling some file functions which are not implemented (fopen, ...). You can check on my other repository (for the newer NumWorks hardware, N110) for an implementation of a sort of a file backend backed by the filesystem storing Pyhton scripts : https://github.com/zardam/nw-external-apps/blob/master/apps/Nofrendo/epsilon/statefile_wrapper.c In this version, the state is saved only at exit, but adding events to do it in game should be very easy. By the way, if you have a N110, you may be more interested by this version (multiple ROM supports, ...), and you can install it easily online : https://zardam.github.io/nw-external-apps/

If not, it should not be too hard to port the savestate function to this repository.

**Comment by maelhos** [comment]
I've a N100 ... I'm curently working on it ... thank you so much !!

**Comment by maelhos** [comment]
Ok ... i understand a bit more now ... but in the version for N110 you've reimplemented the savestate but https://github.com/zardam/numworks-nofrendo/blob/master/nofrendo/event.c#L94 inst already an implementation of it in the emulator itself ?

**Comment by zardam** [comment]
The savestate is not reimplemented. There are just some changes in https://github.com/zardam/nw-external-apps/blob/c79283782177d77c49eb7fb0724e5a00557e890d/apps/Nofrendo/libsnss/libsnss.c in order to not call libc file functions but the ones declared here : https://github.com/zardam/nw-external-apps/blob/c79283782177d77c49eb7fb0724e5a00557e890d/apps/Nofrendo/epsilon/statefile_wrapper.h

I think that if you take libsnss.c from the N110, then implement statefile_wrapper.h functions (with https://github.com/zardam/nw-external-apps/blob/c79283782177d77c49eb7fb0724e5a00557e890d/apps/Nofrendo/epsilon/statefile_wrapper.c as a base) and add the save/load state events in https://github.com/zardam/numworks-nofrendo/blob/master/nofrendo/epsilon/osd_epsilon.c#L91 savestate should be working on the N100 version

**Comment by zardam** [comment]
After digging a little bit more, I found that there was not enough memory on the calculator to do what I told you, and that it was needed to use the standard apps buffer memory in order to have enough free memory (there is also other ways, but needing more rewrite of the emulator than I can actually do on my spare time).

I have done a very ugly hack in memguard.c in order to redirect dynamic memory allocation of the emulator in the apps buffer, and basically implemented the statefile_wrapper in a static buffer. This seems to be working well with the few ROM I tested.

Just push "copy" to save the state, and "paste" to restore it. The state is also saved when exiting the emulator.

The branch is here : https://github.com/zardam/numworks-nofrendo/tree/v12-n110-savestate

**Comment by maelhos** [comment]
Hey, thank you so much !!!
I was working on it and ieach time, it was my problem too ... i just decided to delete the proba app and use static memory instead (thats probably even more ugly than ur solution) and that was very slow and super buggy ... Your solution seems working perfectely on smb1 ...
